### ISSUE TITLE
Removed import

### ISSUE THREAD

**Issue by papachoco** [zopefoundation/zope.configuration#38]
Jason,

In the our application (dataserver) we are using 

```
from zope import interface
from zope.configuration import fields

class IAWSKey(interface.Interface):
    grant = fields.TextLine(title=u"rant type", required=False)
````

in zope.configuration 4.2.1 (fields.py) the ```from zope.schema import TextLine``` line was removed. ( I guess we should be using zope.schema directly). but this may affect other users

Carlos

**Comment by jamadden** [comment]
Thanks for the report. That's not a documented API of that module (https://zopeconfiguration.readthedocs.io/en/latest/api/fields.html), it's an internal implementation detail. Internal implementation details are subject to change at any time.

**Comment by jamadden** [comment]
Assuming your IDE suggested using that detail, what might help would be the addition of `__all__` for the supported API.
